### ISSUE TITLE
Make it possible to initialize SDL with flags other than the default

### ISSUE THREAD

**Issue by Keithcat1** [chrisnorman7/dart_sdl#7]
While Sdl.init accepts a flags parameter, the SDL_INIT_XXX constants don't actually appear to be exposed, so there's no way to use it. I'm planning on only initializing the video subsystem, since audiogames only need that much.

**Comment by chrisnorman7** [comment]
Hi,
You're welcome to either submit a PR, or wait an unknown amount of time for
me to do this.

Take care,

Chris Norman

**Comment by chrisnorman7** [comment]
Also, I just checked the signature for the `Sdl.init` method, and you can provide whatever flags you like, which you can import with `package:dart_sdl/sdl_bindings.dart` or some such.

I'll look more into this when I've fixed the documentation, which apparently hasn't been building since I don't know when.

**Comment by Keithcat1** [comment]
This isn't fixed yet. In order to allow:
```dart
import "package:dart_sdl/sdl_bindings.dart";
```
You need to create a file "sdl_bindings.dart" in your projects lib directory, right next to dart_sdl.dart that exports  lib/src/sdl_bindings.dart. And of course make sure to use the "library" statement with a doc comment above it so that Dartdoc has something to show.

**Comment by chrisnorman7** [comment]
Hi @Keithcat1,
Sorry, I provided you a work around for this a while back, and then forgot to update this issue.

You can now do:

```dart
  final sdl = Sdl()
    ..init(
        flags: InitFlags(
      audio: true,
      events: true,
      sensor: false,
    ).flags);
```

HTH.
